//This code was automatically generated by the Firebase Console.
import { initializeApp } from "firebase/app";
import { getFirestore } from "@firebase/firestore";
import { getAnalytics } from "firebase/analytics";

const firebaseConfig = {
  apiKey: "AIzaSyAShHVKUXYJnNHbs7kRfckAHxPraFMw7jI",
  authDomain: "user-form-8ffd6.firebaseapp.com",
  projectId: "user-form-8ffd6",
  storageBucket: "user-form-8ffd6.appspot.com",
  messagingSenderId: "763038897451",
  appId: "1:763038897451:web:52dd73b058ace184c9216e",
  measurementId: "G-027WK1F2SE"
};

const app = initializeApp(firebaseConfig);
const analytics = getAnalytics(app);
const firestore = getFirestore(app);
export default firestore;